/**
 * Sterling---Associates-Law - Backend Server
 * Auto-generated by Module Library Assembler
 * 
 * Run: npm install && npm run dev
 */

const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
require('dotenv').config();

const app = express();

// ============================================
// MIDDLEWARE
// ============================================

app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: true, credentials: true }));
app.use(morgan('dev'));
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true, limit: '50mb' }));

// ============================================
// MODULE ROUTES (Auto-Wired)
// ============================================

const authRoutes = require('./modules/auth/routes/auth.js');
const admin_dashboardRoutes = require('./modules/admin-dashboard/routes/admin.js');
const analyticsRoutes = require('./modules/analytics/routes/metrics.js');
const admin_apiRoutes = require('./modules/admin-api/routes/analytics.js');
const bookingRoutes = require('./modules/booking/routes/booking.js');
const documentsRoutes = require('./modules/documents/routes/documents.js');
const notificationsRoutes = require('./modules/notifications/routes/notifications.js');

// Register routes
app.use('/api/auth', authRoutes);
app.use('/api/admin', admin_dashboardRoutes);
app.use('/api/analytics', analyticsRoutes);
app.use('/api/admin', admin_apiRoutes);
app.use('/api/booking', bookingRoutes);
app.use('/api/documents', documentsRoutes);
app.use('/api/notifications', notificationsRoutes);

// ============================================
// BRAIN & HEALTH ROUTES (Admin System)
// ============================================

const brainRoutes = require('./routes/brain');
const healthRoutes = require('./routes/health');

app.use('/api/brain', brainRoutes);
app.use('/api/health', healthRoutes);

// Quick health check (legacy)
app.get('/health', (req, res) => {
  res.json({
    status: 'ok',
    project: 'Sterling---Associates-Law',
    timestamp: new Date().toISOString(),
    modules: 7
  });
});

// ============================================
// ERROR HANDLING
// ============================================

app.use((err, req, res, next) => {
  console.error('Error:', err.message);
  res.status(err.status || 500).json({
    error: err.message || 'Internal server error'
  });
});

// 404 handler
app.use((req, res) => {
  res.status(404).json({ error: 'Not found', path: req.path });
});

// ============================================
// START SERVER
// ============================================

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log('');
  console.log('🚀 Sterling---Associates-Law backend running on port ' + PORT);
  console.log('   Health: http://localhost:' + PORT + '/health');
  console.log('   API:    http://localhost:' + PORT + '/api');
  console.log('');
  console.log('📦 Loaded modules (7):');
  console.log('   ✅ auth');
  console.log('   ✅ admin-dashboard');
  console.log('   ✅ analytics');
  console.log('   ✅ admin-api');
  console.log('   ✅ booking');
  console.log('   ✅ documents');
  console.log('   ✅ notifications');
});

module.exports = app;
