/**
 * Database Setup Script
 * Auto-generated by Module Library Assembler
 * 
 * Run: node setup-db.js
 * This will create all required tables if they don't exist
 */

require('dotenv').config();
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false
});

const tables = {
  // Users table (auth module)
  users: `
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      email VARCHAR(255) UNIQUE NOT NULL,
      password_hash VARCHAR(255) NOT NULL,
      full_name VARCHAR(255),
      phone VARCHAR(50),
      subscription_tier VARCHAR(50) DEFAULT 'free',
      is_admin BOOLEAN DEFAULT false,
      scans_used INTEGER DEFAULT 0,
      referred_by VARCHAR(50),
      referral_code_id INTEGER,
      referred_at TIMESTAMP,
      reset_token VARCHAR(255),
      reset_token_expires TIMESTAMP,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Bookings table (booking module)
  bookings: `
    CREATE TABLE IF NOT EXISTS bookings (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id),
      customer_name VARCHAR(255) NOT NULL,
      customer_email VARCHAR(255),
      customer_phone VARCHAR(50),
      service_type VARCHAR(100) DEFAULT 'general',
      booking_date DATE NOT NULL,
      start_time TIME NOT NULL,
      end_time TIME,
      party_size INTEGER DEFAULT 1,
      notes TEXT,
      status VARCHAR(50) DEFAULT 'pending',
      cancellation_reason TEXT,
      cancelled_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Contact submissions
  contact_submissions: `
    CREATE TABLE IF NOT EXISTS contact_submissions (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL,
      phone VARCHAR(50),
      subject VARCHAR(255),
      message TEXT NOT NULL,
      status VARCHAR(50) DEFAULT 'new',
      responded_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Referral codes (auth module)
  referral_codes: `
    CREATE TABLE IF NOT EXISTS referral_codes (
      id SERIAL PRIMARY KEY,
      code VARCHAR(50) UNIQUE NOT NULL,
      user_id INTEGER REFERENCES users(id),
      total_signups INTEGER DEFAULT 0,
      active BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Services/Products
  services: `
    CREATE TABLE IF NOT EXISTS services (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      description TEXT,
      price DECIMAL(10, 2),
      duration_minutes INTEGER,
      category VARCHAR(100),
      active BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Reviews/Testimonials
  reviews: `
    CREATE TABLE IF NOT EXISTS reviews (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id),
      booking_id INTEGER REFERENCES bookings(id),
      rating INTEGER CHECK (rating >= 1 AND rating <= 5),
      title VARCHAR(255),
      content TEXT,
      approved BOOLEAN DEFAULT false,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Newsletter subscribers
  subscribers: `
    CREATE TABLE IF NOT EXISTS subscribers (
      id SERIAL PRIMARY KEY,
      email VARCHAR(255) UNIQUE NOT NULL,
      name VARCHAR(255),
      subscribed BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Customers (CRM)
  customers: `
    CREATE TABLE IF NOT EXISTS customers (
      id SERIAL PRIMARY KEY,
      email VARCHAR(255) UNIQUE NOT NULL,
      full_name VARCHAR(255),
      phone VARCHAR(50),
      address TEXT,
      city VARCHAR(100),
      state VARCHAR(100),
      zip_code VARCHAR(20),
      country VARCHAR(100) DEFAULT 'US',
      customer_type VARCHAR(50) DEFAULT 'regular',
      lifetime_value DECIMAL(10, 2) DEFAULT 0,
      total_orders INTEGER DEFAULT 0,
      last_order_date TIMESTAMP,
      notes TEXT,
      tags TEXT[],
      source VARCHAR(100),
      active BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Customer communications
  customer_communications: `
    CREATE TABLE IF NOT EXISTS customer_communications (
      id SERIAL PRIMARY KEY,
      customer_id INTEGER REFERENCES customers(id) ON DELETE CASCADE,
      type VARCHAR(50) NOT NULL,
      subject VARCHAR(255),
      content TEXT,
      direction VARCHAR(20) DEFAULT 'outbound',
      status VARCHAR(50) DEFAULT 'sent',
      metadata JSONB DEFAULT '{}',
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Products/Inventory
  products: `
    CREATE TABLE IF NOT EXISTS products (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      sku VARCHAR(100) UNIQUE,
      description TEXT,
      price DECIMAL(10, 2),
      cost DECIMAL(10, 2),
      quantity INTEGER DEFAULT 0,
      low_stock_threshold INTEGER DEFAULT 10,
      category VARCHAR(100),
      image_url TEXT,
      active BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Inventory movements
  inventory_movements: `
    CREATE TABLE IF NOT EXISTS inventory_movements (
      id SERIAL PRIMARY KEY,
      product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
      adjustment INTEGER NOT NULL,
      reason VARCHAR(255),
      reference_type VARCHAR(50),
      reference_id INTEGER,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Orders
  orders: `
    CREATE TABLE IF NOT EXISTS orders (
      id SERIAL PRIMARY KEY,
      order_number VARCHAR(50) UNIQUE NOT NULL,
      customer_id INTEGER REFERENCES customers(id),
      items JSONB NOT NULL DEFAULT '[]',
      subtotal DECIMAL(10, 2) DEFAULT 0,
      tax DECIMAL(10, 2) DEFAULT 0,
      shipping DECIMAL(10, 2) DEFAULT 0,
      total DECIMAL(10, 2) DEFAULT 0,
      status VARCHAR(50) DEFAULT 'pending',
      payment_status VARCHAR(50) DEFAULT 'unpaid',
      payment_method VARCHAR(50),
      shipping_address TEXT,
      billing_address TEXT,
      tracking_number VARCHAR(100),
      notes TEXT,
      shipped_at TIMESTAMP,
      delivered_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Order returns
  order_returns: `
    CREATE TABLE IF NOT EXISTS order_returns (
      id SERIAL PRIMARY KEY,
      order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
      reason TEXT,
      items JSONB DEFAULT '[]',
      refund_amount DECIMAL(10, 2),
      status VARCHAR(50) DEFAULT 'pending',
      notes TEXT,
      processed_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Competitors tracking
  competitors: `
    CREATE TABLE IF NOT EXISTS competitors (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      website VARCHAR(255),
      description TEXT,
      strengths TEXT,
      weaknesses TEXT,
      price_range VARCHAR(100),
      rating DECIMAL(3, 2),
      review_count INTEGER DEFAULT 0,
      location VARCHAR(255),
      distance DECIMAL(5, 2),
      last_checked TIMESTAMP,
      notes TEXT,
      active BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Competitor analysis history
  competitor_analysis: `
    CREATE TABLE IF NOT EXISTS competitor_analysis (
      id SERIAL PRIMARY KEY,
      competitor_id INTEGER REFERENCES competitors(id) ON DELETE CASCADE,
      analysis_type VARCHAR(50),
      content TEXT,
      insights JSONB DEFAULT '{}',
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Analytics events
  analytics_events: `
    CREATE TABLE IF NOT EXISTS analytics_events (
      id SERIAL PRIMARY KEY,
      event_type VARCHAR(100) NOT NULL,
      page VARCHAR(255),
      user_id INTEGER,
      session_id VARCHAR(100),
      metadata JSONB DEFAULT '{}',
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Staging content (draft edits)
  staging_content: `
    CREATE TABLE IF NOT EXISTS staging_content (
      id SERIAL PRIMARY KEY,
      selector VARCHAR(500) UNIQUE NOT NULL,
      element_type VARCHAR(50) NOT NULL,
      content TEXT,
      styles JSONB DEFAULT '{}',
      status VARCHAR(20) DEFAULT 'draft',
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Production content (published overrides)
  production_content: `
    CREATE TABLE IF NOT EXISTS production_content (
      id SERIAL PRIMARY KEY,
      selector VARCHAR(500) UNIQUE NOT NULL,
      element_type VARCHAR(50) NOT NULL,
      content TEXT,
      styles JSONB DEFAULT '{}',
      published_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Content history (version tracking)
  content_history: `
    CREATE TABLE IF NOT EXISTS content_history (
      id SERIAL PRIMARY KEY,
      selector VARCHAR(500) NOT NULL,
      element_type VARCHAR(50) NOT NULL,
      content TEXT,
      styles JSONB DEFAULT '{}',
      action VARCHAR(20) NOT NULL,
      published_by INTEGER REFERENCES users(id),
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Site theme settings
  site_theme: `
    CREATE TABLE IF NOT EXISTS site_theme (
      id SERIAL PRIMARY KEY,
      theme_name VARCHAR(100) DEFAULT 'default',
      primary_color VARCHAR(20) DEFAULT '#3B82F6',
      secondary_color VARCHAR(20) DEFAULT '#10B981',
      accent_color VARCHAR(20) DEFAULT '#F59E0B',
      font_family VARCHAR(100) DEFAULT 'Inter',
      is_draft BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Staging assets (uploaded images)
  staging_assets: `
    CREATE TABLE IF NOT EXISTS staging_assets (
      id SERIAL PRIMARY KEY,
      filename VARCHAR(255) NOT NULL,
      original_name VARCHAR(255),
      mime_type VARCHAR(100),
      file_size INTEGER,
      url TEXT NOT NULL,
      selector VARCHAR(500),
      is_draft BOOLEAN DEFAULT true,
      uploaded_by INTEGER REFERENCES users(id),
      created_at TIMESTAMP DEFAULT NOW()
    )
  `
};

async function setupDatabase() {
  console.log('🗄️  Setting up database...\n');

  try {
    // Test connection
    await pool.query('SELECT NOW()');
    console.log('✅ Database connected\n');

    // Create each table
    for (const [tableName, createSQL] of Object.entries(tables)) {
      try {
        await pool.query(createSQL);
        console.log(`✅ Table "${tableName}" ready`);
      } catch (err) {
        console.error(`❌ Failed to create "${tableName}":`, err.message);
      }
    }

    // Create indexes for performance
    console.log('\n📊 Creating indexes...');

    const indexes = [
      // Core tables
      'CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)',
      'CREATE INDEX IF NOT EXISTS idx_bookings_date ON bookings(booking_date)',
      'CREATE INDEX IF NOT EXISTS idx_bookings_user ON bookings(user_id)',
      'CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status)',
      'CREATE INDEX IF NOT EXISTS idx_contact_status ON contact_submissions(status)',
      // Customers
      'CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email)',
      'CREATE INDEX IF NOT EXISTS idx_customers_type ON customers(customer_type)',
      'CREATE INDEX IF NOT EXISTS idx_customers_active ON customers(active)',
      'CREATE INDEX IF NOT EXISTS idx_customer_comms_customer ON customer_communications(customer_id)',
      // Products/Inventory
      'CREATE INDEX IF NOT EXISTS idx_products_sku ON products(sku)',
      'CREATE INDEX IF NOT EXISTS idx_products_category ON products(category)',
      'CREATE INDEX IF NOT EXISTS idx_products_active ON products(active)',
      'CREATE INDEX IF NOT EXISTS idx_inventory_movements_product ON inventory_movements(product_id)',
      // Orders
      'CREATE INDEX IF NOT EXISTS idx_orders_number ON orders(order_number)',
      'CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id)',
      'CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status)',
      'CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at)',
      'CREATE INDEX IF NOT EXISTS idx_order_returns_order ON order_returns(order_id)',
      // Competitors
      'CREATE INDEX IF NOT EXISTS idx_competitors_active ON competitors(active)',
      'CREATE INDEX IF NOT EXISTS idx_competitor_analysis_competitor ON competitor_analysis(competitor_id)',
      // Analytics
      'CREATE INDEX IF NOT EXISTS idx_analytics_type ON analytics_events(event_type)',
      'CREATE INDEX IF NOT EXISTS idx_analytics_session ON analytics_events(session_id)',
      'CREATE INDEX IF NOT EXISTS idx_analytics_created ON analytics_events(created_at)',
      // Staging content
      'CREATE INDEX IF NOT EXISTS idx_staging_content_selector ON staging_content(selector)',
      'CREATE INDEX IF NOT EXISTS idx_staging_content_status ON staging_content(status)',
      'CREATE INDEX IF NOT EXISTS idx_production_content_selector ON production_content(selector)',
      'CREATE INDEX IF NOT EXISTS idx_content_history_selector ON content_history(selector)',
      'CREATE INDEX IF NOT EXISTS idx_content_history_created ON content_history(created_at)',
      'CREATE INDEX IF NOT EXISTS idx_staging_assets_selector ON staging_assets(selector)',
      'CREATE INDEX IF NOT EXISTS idx_staging_assets_draft ON staging_assets(is_draft)'
    ];

    for (const idx of indexes) {
      try {
        await pool.query(idx);
      } catch (err) {
        // Index might already exist, that's fine
      }
    }
    console.log('✅ Indexes created\n');

    // Seed admin user if ADMIN_EMAIL and ADMIN_PASSWORD are set
    await seedAdminUser();

    // Summary
    const tableCount = await pool.query(`
      SELECT COUNT(*) FROM information_schema.tables
      WHERE table_schema = 'public'
    `);

    console.log('═══════════════════════════════════════');
    console.log(`✅ Database setup complete!`);
    console.log(`   Tables: ${tableCount.rows[0].count}`);
    console.log('═══════════════════════════════════════\n');

  } catch (error) {
    console.error('❌ Database setup failed:', error.message);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

/**
 * Seed admin user from environment variables
 * Only creates if ADMIN_EMAIL and ADMIN_PASSWORD are set
 */
async function seedAdminUser() {
  const adminEmail = process.env.ADMIN_EMAIL;
  const adminPassword = process.env.ADMIN_PASSWORD;

  if (!adminEmail || !adminPassword) {
    console.log('⚠️  ADMIN_EMAIL/ADMIN_PASSWORD not set - skipping admin seeding');
    return;
  }

  console.log('\n👤 Seeding admin user...');

  try {
    // Check if admin already exists
    const existingResult = await pool.query(
      'SELECT id FROM users WHERE email = $1',
      [adminEmail]
    );

    if (existingResult.rows.length > 0) {
      // Update existing admin password
      const bcrypt = require('bcryptjs');
      const passwordHash = await bcrypt.hash(adminPassword, 10);

      await pool.query(
        'UPDATE users SET password_hash = $1, is_admin = true, updated_at = NOW() WHERE email = $2',
        [passwordHash, adminEmail]
      );
      console.log(`✅ Admin user updated: ${adminEmail}`);
    } else {
      // Create new admin user
      const bcrypt = require('bcryptjs');
      const passwordHash = await bcrypt.hash(adminPassword, 10);

      await pool.query(
        `INSERT INTO users (email, password_hash, full_name, is_admin, subscription_tier, created_at, updated_at)
         VALUES ($1, $2, $3, true, 'admin', NOW(), NOW())`,
        [adminEmail, passwordHash, 'Admin']
      );
      console.log(`✅ Admin user created: ${adminEmail}`);
    }
  } catch (err) {
    console.error('⚠️  Could not seed admin user:', err.message);
  }
}

// Run setup
setupDatabase();